### ISSUE TITLE
{"statusCode":400,"error":"Bad Request","message":"Browser client is out of date, please refresh the page (\"kbn-version\" header was \"7.11.2\" but should be \"7.12.0\""

### ISSUE THREAD

**Issue by mmurph3** [hcw2016/kofe-docker#2]
mmurphy@ubuntu:~/kofe-docker/scripts$ bash index-manage.sh
Enter Elasticsearch Password: changeme
Error generating OSSEC index.
HTTP/1.1 400 Bad Request
kbn-name: kibana
kbn-license-sig: c19993aacb2c0a4bf9a655a2a73a57beefa6ca7345013cb8032f8aaeb16e0fa7
content-type: application/json; charset=utf-8
cache-control: private, no-cache, no-store, must-revalidate
content-length: 222
Date: Thu, 01 Apr 2021 20:42:12 GMT
Connection: keep-alive
Keep-Alive: timeout=120
{"statusCode":400,"error":"Bad Request","message":"Browser client is out of date, please refresh the page (\"kbn-version\" header was \"7.11.2\" but should be \"7.12.0\")","attributes":{"expected":"7.12.0","got":"7.11.2"}}m

**Comment by hcw2016** [comment]
Added version bump in index-manage.sh
